services:
    GeekCell\KafkaBundle\Kafka\Context:
        arguments:
            - '@RdKafka\Producer'
            - '@GeekCell\KafkaBundle\Serializer\Factory\SerializerFactoryProducer'
            - '@GeekCell\KafkaBundle\Support\Resolver\DefaultTopicNameResolver'
        public: true

    GeekCell\KafkaBundle\EventSubscriber\KafkaSubscriber:
        arguments:
            - '@GeekCell\KafkaBundle\Kafka\Context'
        tags:
            - { name: kernel.event_subscriber }
        public: false

    GeekCell\KafkaBundle\Serializer\GenericEventSerializer:
        factory:
            - '@GeekCell\KafkaBundle\Serializer\Factory\GenericEventSerializerFactory'
            - create
        public: false

    GeekCell\KafkaBundle\Serializer\RecordSerializer:
        factory:
            - '@GeekCell\KafkaBundle\Serializer\Factory\RecordSerializerFactory'
            - create
        public: false

    GeekCell\KafkaBundle\Serializer\Factory\GenericEventSerializerFactory:
        arguments:
            - '@FlixTech\AvroSerializer\Objects\RecordSerializer'
            - '@GeekCell\KafkaBundle\Serializer\RecordSerializer'
            - '@GeekCell\KafkaBundle\Util\AvroUtil'
            - '%geek_cell_kafka.avro.schemas.defaults%'
        tags:
            - { name: geek_cell_kafka.serializer_factory }
        public: false

    GeekCell\KafkaBundle\Serializer\Factory\RecordSerializerFactory:
        arguments:
            - '@FlixTech\AvroSerializer\Objects\RecordSerializer'
            - '@GeekCell\KafkaBundle\Util\AvroUtil'
            - '%geek_cell_kafka.avro.schemas.defaults%'
        tags:
            - { name: geek_cell_kafka.serializer_factory }
        public: false

    GeekCell\KafkaBundle\Serializer\Factory\SerializerFactoryProducer:
        public: false

    GeekCell\KafkaBundle\Support\Resolver\DefaultTopicNameResolver:
        public: false

    GeekCell\KafkaBundle\Util\AvroUtil:
        public: false

    FlixTech\AvroSerializer\Objects\RecordSerializer:
        factory:
            - '@FlixTech\AvroSerializer\Objects\DefaultRecordSerializerFactory'
            - get
        arguments:
            - '%geek_cell_kafka.avro.schema_registry_url%'
        public: false

    FlixTech\AvroSerializer\Objects\DefaultRecordSerializerFactory:
        public: false
